### ISSUE TITLE
Unschlüssige Charaktere

### ISSUE THREAD

**Issue by AnnaBronec** [georgbuechner/Spaetes-Theater#4]
Uns sind gerade beim durchgehen der Charaktere aufgefallen, dass ein paar Charaktere zwar an sich sehr interessant sind aber zum Teil vielleicht einbisschen der Zusammenhang zu anderen Charakteren fehlt. Zudem haben wir eh einbisschen zu viele Leute. Da das aber eine sehr wichtige Entscheidung ist wäre das glaube ich gut zusammen darüber zu disskutieren. Wir haben mal alle Charaktere in der MindMap mit Sternchen makiert, auf die man theoretisch verzichten könnte aber nicht muss. Von daher schaut euch das doch mal an und wir schauen dann mal zusammen zu wem uns noch coole Storylines einfallen oder auf wen wir eventuell verzichten könnten.

**Comment by georgbuechner** [comment]
Charaktere sind nun final ausgewählt.
