### ISSUE TITLE
Wieso mag keiner den Einstein?

### ISSUE THREAD

**Issue by ronjahuet** [georgbuechner/Spaetes-Theater#8]
Wurden die "feindlichen" Beziehungspfeile in der Mindmap mit Sinn gesetzt hinsichtlich Einstein? Hattet Ihr euch was dazu was überlegt? Einstein lebt nach dem Kausalitätsprinzip von Newton, hat daher eine eher positive Verbindung zu ihm. Wir wollten einfach nochmal fragen, woher die Idee kam :) @georgbuechner @AnnaBronec

**Comment by georgbuechner** [comment]
In der ursprünglichen Variante waren ja die anderen im Irrenhaus, also von den Physikern alle außer Einstein. Darum die negativen Beziehungspfeile. Allerdings war auch die nur beispielhaft gesetzt, wie ich mich erinnere, also es gab ne Idee dahinter, aber wir haben es glaube ich auch gemacht, damit es einfach mal, ein paar Pfeile gibt und man was zum gucken hat ;) 

Von meiner Seite aus: macht darauf, was ihr wollt.
